# Generated by Django 3.0.7 on 2020-06-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('desc', models.CharField(max_length=1024)),
                ('img', models.ImageField(upload_to='acpl/img/')),
                ('refr', models.CharField(blank=True, max_length=512)),
                ('categories', models.CharField(max_length=128)),
                ('url', models.URLField(blank=True)),
                ('pfile', models.FileField(upload_to='acpl/files/')),
            ],
        ),
    ]
