# Generated by Django 3.0.7 on 2020-06-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('desg', models.CharField(max_length=64)),
                ('pic', models.ImageField(upload_to='acpl/img')),
                ('linkd', models.URLField(blank=True)),
            ],
        ),
    ]
