# Generated by Django 3.0.7 on 2020-06-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200629_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.CharField(choices=[('DMARKETING', 'Digital Marketing'), ('WDESIGN', 'Web Development & Design'), ('MSOLUTIONS', 'Marketing Solutions'), ('RANALYTICS', 'Research & Analytics')], default='DMARKETING', max_length=128),
        ),
    ]
