# Generated by Django 3.0.7 on 2020-06-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20200629_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.CharField(choices=[('Digital Marketing', 'Digital Marketing'), ('Web Development & Design', 'Web Development & Design'), ('Marketing Solutions', 'Marketing Solutions'), ('Research & Analytics', 'Research & Analytics')], default='Digital Marketing', max_length=128),
        ),
    ]
