# Generated by Django 3.0.7 on 2020-06-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20200629_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.CharField(choices=[('dmarketing', 'Digital Marketing'), ('wdesign', 'Web Development & Design'), ('msolutions', 'Marketing Solutions'), ('ranalytics', 'Research & Analytics')], default='Digital Marketing', max_length=128),
        ),
    ]
