# Generated by Django 3.0.7 on 2020-06-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acpl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('desc', models.CharField(max_length=1024)),
                ('img', models.ImageField(upload_to='Cases/img/')),
                ('refr', models.CharField(blank=True, max_length=512)),
                ('categories', models.CharField(max_length=128)),
                ('url', models.URLField(blank=True)),
                ('pfile', models.FileField(upload_to='Cases/files/')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('desg', models.CharField(max_length=64)),
                ('pic', models.ImageField(upload_to='Teams/img')),
                ('linkd', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='categories',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='blogs',
            name='refr',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='blogs',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='desc',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
