# Generated by Django 3.0.7 on 2020-06-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acpl', '0002_auto_20200626_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='img',
            field=models.ImageField(upload_to='acpl/img/'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='img',
            field=models.ImageField(upload_to='acpl/img/'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='pfile',
            field=models.FileField(upload_to='acpl/files/'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='pic',
            field=models.ImageField(upload_to='acpl/img'),
        ),
    ]
