# Generated by Django 3.0.7 on 2020-06-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acpl', '0003_auto_20200626_1211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='Cases',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
